### ISSUE TITLE
JWT guide instructions incorrect

### ISSUE THREAD

**Issue by gbengataylor** [quarkusio/quarkusio.github.io#217]
after following the instructions (https://quarkus.io/guides/jwt-guide) to generate the project and run the application the first time, the following error is received
```
17:05:50,656 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:121)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:159)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:93)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl1.<clinit>(Unknown Source)
        ... 8 more
Caused by: java.util.NoSuchElementException: No value present
        at java.util.Optional.get(Optional.java:135)
        at io.smallrye.jwt.config.JWTAuthContextInfoProvider.getContextInfo(JWTAuthContextInfoProvider.java:200)
        at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.create(Unknown Source)
        at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.get(Unknown Source)
        at io.smallrye.jwt.config.JWTAuthContextInfoProvider_ProducerMethod_getContextInfo_21d111677ae04ef1a7cf911100af3482e4c3b30a_Bean.get(Unknown Source)
        at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMethodExtension_Bean.create(Unknown Source)
        at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMethodExtension_Bean.get(Unknown Source)
        at io.quarkus.smallrye.jwt.runtime.auth.JWTAuthMethodExtension_Bean.get(Unknown Source)
        at io.quarkus.arc.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:310)
        at io.quarkus.arc.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:322)
        at io.quarkus.arc.ArcContainerImpl$1.get(ArcContainerImpl.java:201)
        at io.quarkus.arc.ArcContainerImpl$1.get(ArcContainerImpl.java:198)
        at io.quarkus.arc.runtime.ArcDeploymentTemplate$2$1.create(ArcDeploymentTemplate.java:86)
        at io.quarkus.arc.runtime.BeanContainer.instance(BeanContainer.java:35)
        at io.quarkus.smallrye.jwt.runtime.SmallRyeJwtTemplate.createAuthExtension(SmallRyeJwtTemplate.java:41)
        at io.quarkus.deployment.steps.SmallRyeJwtProcessor$registerJwtAuthExtension12.deploy(Unknown Source)
        ... 9 more
```
It appears the instructions to update application.properties with this value is missing
```
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem
```
Once added the app deploys correctly. The instructions should reflect that

If the instructions are correct but the problem is with the smallrey-jwt extensiion I'll enter an issue in that repo

**Comment by gsmet** [comment]
@starksm64 could you take a look at this one? Thanks!

**Comment by gsmet** [comment]
Thanks for the report, this has been fixed in the guide a while ago.
