### ISSUE TITLE
Spring DI/Web/Data gotchas

### ISSUE THREAD

**Issue by jamesfalkner** [quarkusio/quarkusio.github.io#289]
I ran into a few non-obvious gotchas while developing a tutorial for Spring Web/DI/Data so I thought I'd mention them here for possible inclusion into the guides.

* You have to use `@PathVariable(name = "foo") int foo` in controller methods -- with "ordinary" spring you can skip the `(name = "foo")` bit if the name of the path variable and name of the method argument are the same, I assume spring does magic reflection match the argument name with the path variable name. But it doesn't work with Quarkus.

* controller methods cannot return a `JsonObject` (from vertx) - it doesn't fail but it does give empty results. I would have expected complete failure or stack trace. In any case, this is documented at https://quarkus.io/guides/spring-web-guide but in other Guides (most notably the Vert.x one) there are resource methods that return `JsonObject` so i tried that initially.

* (@jclingan mentioned this, but I didn't try this) you also have to have `@RequestMapping` on class level, but in Spring it can be on method only.

* If I define an entity with an `@Id` like this:
    ```java
    @Id
    @GeneratedValue
    private Long id;
    ```
    And then I have an `import.sql` that creates an entity with `id=1`, for example:
    ```sql
    INSERT INTO fruit(id, name, color) VALUES (1, 'cherry', 'red');
    ```
    Then if I try to call a method which tries to `.save()` a new instance (e.g. `fruitRepository.save(new Fruit(name, color));` It fails.

Postgres complains:

```
2019-09-10 19:08:04.990 UTC [69] ERROR:  duplicate key value violates unique constraint "fruit_pkey"
2019-09-10 19:08:04.990 UTC [69] DETAIL:  Key (id)=(1) already exists.
2019-09-10 19:08:04.990 UTC [69] STATEMENT:  insert into Fruit (color, name, id) values ($1, $2, $3)
```

And Quarkus complains:

```
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "fruit_pkey"
  Detail: Key (id)=(1) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2468)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2211)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:309)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:124)
        at io.agroal.pool.wrapper.PreparedStatementWrapper.executeUpdate(PreparedStatementWrapper.java:85)
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:175)
        ... 105 more
```

Since I had 5 entries in my `import.sql` my workaround was to:

```java
    @Id
    @SequenceGenerator(name = "fruitGen", sequenceName = "fruitGen", initialValue = 6, allocationSize = 1)
    @GeneratedValue(generator = "fruitGen")
    private Long id;
```

Setting the `initialValue` to `6` to avoid the first 5 already present.

**Comment by jclingan** [comment]
Well, with RequestMapping in Spring it's not on method only - it can be class and/or method. With Quarkus Spring Web there has to be a RequestMapping on the class.

**Comment by geoand** [comment]
Issue #3992 is waiting for a RESTEasy release to be fixed.

**Comment by gsmet** [comment]
@geoand can we close this one?

**Comment by geoand** [comment]
Good idea, yes! The issues mentioned here have been addressed.
