### ISSUE TITLE
Hibernate Validator guide has wrong code

### ISSUE THREAD

**Issue by fmhwong** [quarkusio/quarkusio.github.io#433]
Guide: https://quarkus.io/guides/validation

The `Result` class in the guide is `private`.

```
private class Result {

    Result(String message) {
        this.success = true;
        this.message = message;
    }

    Result(Set<? extends ConstraintViolation<?>> violations) {
        this.success = false;
        this.message = violations.stream()
             .map(cv -> cv.getMessage())
             .collect(Collectors.joining(", "));
    }

    private String message;
    private boolean success;

    public String getMessage() {
        return message;
    }

    public boolean isSuccess() {
        return success;
    }

}
``` 

and I got this exception when running with `private Result`

```
Caused by: java.lang.IllegalAccessException: Class org.eclipse.yasson.internal.model.GetFromGetter can not access a member of class org.acme.validation.BookResource$Result with modifiers "public"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Method.invoke(Method.java:491)
	at org.eclipse.yasson.internal.model.GetFromGetter.internalGetValue(GetFromGetter.java:28)
	at org.eclipse.yasson.internal.model.GetValueCommand.getValue(GetValueCommand.java:34)
	... 40 more
```

The sample code in git has it in `public`.  See https://github.com/quarkusio/quarkus-quickstarts/blob/dbefe831e917d7dabf3bcb2b033098ebaf45146a/validation-quickstart/src/main/java/org/acme/validation/BookResource.java#L63

**Comment by gsmet** [comment]
Thanks. It has already been fixed in master. Will be published next week when we release.

Make it `public static` and it will be ok.

**Comment by gsmet** [comment]
FYI, master for the doc is hosted here: https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/validation.adoc .

It's published on the website when we release.
